class Immatriculation < ActiveRecord::Base
  # nojo:
  # type_annonce:
  # numero_annonce:
  # numero_departement:
  # tribunal:
  # siren:
  # code_rcs:
  # nom_greffe_immat:
  # denomination:
  # administration:
  # montant_capital:
  # devise:
  # forme_juridique:
  # type_voie:
  # numero_voie:
  # nom_voie:
  # code_postal:
  # ville:
  # origine_fonds:
  # qualite_etablissement:
  # activite:
  # date_commencement_activite:
  # date_immatriculation:
  # descriptif:
  # date_effet:
  # journal:
  # opposition:
  # declaration_creance:
  # categorie:
  # immatriculation:
  # nom_publication_ap:
  # numero_parution_ap:
  # date_parution_ap:
  # numero_annonce_ap:
  # file:
  # type_bodacc:
  # annee_parution:
end
