class Modification < ActiveRecord::Base
  # nojo:
  # type_annonce:
  # numero_annonce:
  # numero_departement:
  # tribunal:
  # siren:
  # code_rcs:
  # nom_greffe_immat:
  # denomination:
  # sigle:
  # forme_juridique:
  # date_commencement_activite:
  # date_effet:
  # descriptif:
  # denomination_pepm:
  # siren_pepm:
  # nature_pepp:
  # nom_pepp:
  # prenom_pepp:
  # nom_usage_pepp:
  # siren_pepp:
  # nom_publication_ap:
  # numero_parution_ap:
  # date_parution_ap:
  # numero_annonce_ap:
  # file:
  # type_bodacc:
  # annee_parution:
end
